### ISSUE TITLE
Event Markers of .acq data from Biopac

### ISSUE THREAD

**Issue by iPsych** [bachlab/PsPM#140] opened 2020-08-06 00:51 UTC
### Summary

Event markers of acq files are not imported during both 1)direct .acq import 2)bioread converted .acq.
- I confirmed that the event marker info is saved in .mat file after bioread convert of .acq to .mat.
- When the raw marker channel is imported (i.e. 31th channel received trigger signal), it an be imported as 'marker channel, but loose all information like tag.
- To import the .acq properly, should I need multiple marker channel contains certain marker info (i.e. one channel for onset, one channel for failed response etc...)?

### Technical Info
* PsPM revision ID: 4.3.0 
* MATLAB version: R2020a

**Comment by irojkov-ph** [comment] 2020-08-10 06:27
Dear iPsych,
Thank you for reporting this issue and excuse us for the late response. 

May I ask you to provide more information of the error messages you get and how to reproduce your issue please ? Ideally, it would me good to also have the ".acq" file that you are trying to import, so if you can/want to share it just load it here or send it to me at ivan.rojkov@uzh.ch .

Few comments about BIOPAC's AcqKnowledge files importation:
- The **direct ".acq" import** (datatype=`acq`) in PsPM works only for acq files from **version 2.0 to 3.9.0**
- In the case of newer version files, we recommend first of all to **transform the ".acq" file into a ".mat" file directly in the BIOPAC's AcqKnowledge** and then import it into PsPM using `acqmat` datatype.
- If the previous step is not possible, you **can use the third party library "Bioread"** to first transform the ".acq" file into a ".mat" file and then import it into PsPM using `acq_bioread` datatype.

I hope that it will help a little bit. I hold on for your answer to provide you a more complete answer/support.

Best,
Ivan.

**Comment by irojkov-ph** [comment] 2020-08-19 21:39
@iPsych  Since I haven't received any news from you, I'll close this issue for now, but feel free to reopen it if it's not fixed yet or open a new one it your problem changed :wink:

**Closed by irojkov-ph** 2020-08-19 21:39 UTC
Labels: help wanted
