### ISSUE TITLE
MATLAB2014a, “Error while evaluating uicontrol Callback ”

### ISSUE THREAD

**Issue by Wendy67** [bachlab/PsPM#112] opened 2020-05-05 02:06 UTC
### Summary
although I use MATLAB2014a ，“Error while evaluating uicontrol Callback ”，how I can solve this problem

this probelm happen when I use "import"
### Technical Info
* PsPM revision ID:4.3.0
* MATLAB version:2014a

**Comment by irojkov-ph** [comment] 2020-05-05 07:10
Hi Wendy,
May I ask you to provide us a little bit more information on your issue please ? Only one sentence from the whole error message is unfortunately not enough. 
- What kind of file are you trying to import ?
- Can you please copy-paste the whole error message or take a screenshot of it ? 

A preliminary guess: some PsPM functions use new Matlab features (e.g. `startWith` from Matlab 2016) and it could then represent an issue when you try to use these functions with an older version of Matlab. We are aware of this inconsistencies and trying to avoid and change that. 

I let you answer these two questions and I'll try to come up with a nice solution for you.

**Comment by Wendy67** [comment] 2020-05-05 07:55
Thanks for reply. the first question: I just try to import the example dataset on the PsPM website. but it can't let in when I put on the button "import"
the second question:

——wendy








------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"irojkov-ph"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月5日(星期二) 下午3:10
收件人:&nbsp;"bachlab/PsPM"<PsPM@noreply.github.com&gt;;
抄送:&nbsp;"温秀娟"<765487253@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [bachlab/PsPM] although I use MATLAB2014a ，“Error while evaluating uicontrol Callback ”，how I can solve this problem (#112)





 
Hi Wendy,
 May I ask you to provide us a little bit more information on your issue please ? Only one sentence from the whole error message is unfortunately not enough.
  
What kind of file are you trying to import ?
 
Can you please copy-paste the whole error message or take a screenshot of it ?
  
A preliminary guess: some PsPM functions use new Matlab features (e.g. startWith from Matlab 2016) and it could then represent an issue when you try to use these functions with an older version of Matlab. We are aware of this inconsistencies and trying to avoid and change that.
 
I let you answer these two questions and I'll try to come up with a nice solution for you.

**Comment by irojkov-ph** [comment] 2020-05-05 08:38
Sorry there is no answer for the second question (if you tried to send a picture to GitHub via email maybe it does not work). And for the first one can you be more precise, which exactly dataset from PsPM ? What kind of data (pupil, scr, emg, ...) ?

**Comment by Wendy67** [comment] 2020-05-05 08:52
the first question: no more detail. it just happen beginning. the dataset is no wrong.
the second question :
出错 cfg_util (line 428)
rev = '$Rev: 380 $';

调用 "C:\Program
Files\MATLAB\R2014a\toolbox\pspm\ext\matlabbatch\cfg_util.m&gt;cfg_util" 时，未对输出参数
"varargout" (可能还包括其他参数)赋值。

出错 cfg_add_module (line 9)
mod_job_id = cfg_util('addtojob', cjob, mod_cfg_id);

出错 pspm&gt;ppDataPreparation_Callback (line 354)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; cfg_add_module('pspm.prep.import');

出错 gui_mainfcn (line 95)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; feval(varargin{:});

出错 pspm (line 55)
&nbsp;&nbsp;&nbsp; gui_mainfcn(gui_State, varargin{:});

出错
@(hObject,eventdata)pspm('ppDataPreparation_Callback',hObject,eventdata,guidata(hObject))

&nbsp;
Error while evaluating uicontrol Callback


——Wendy





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "irojkov-ph"<notifications@github.com&gt;; 
发送时间: 2020年5月5日(星期二) 下午4:38
收件人: "bachlab/PsPM"<PsPM@noreply.github.com&gt;; 
抄送: "温秀娟"<765487253@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [bachlab/PsPM] although I use MATLAB2014a ，“Error while evaluating uicontrol Callback ”，how I can solve this problem (#112)





 
Sorry there is no answer for the second question (if you tried to send a picture to GitHub via email maybe it does not work). And for the first one can you be more precise, which exactly dataset from PsPM ? What kind of data (pupil, scr, emg, ...) ?

**Comment by fmelinscak** [comment] 2020-05-05 10:18
One way for this error to occur is to clear the Matlab workspace with "clear all;" after initiating the PsPM GUI with "pspm;". Once PsPM is initialized, the memory shouldn't be cleared. Could you confirm if this is what happened?

**Comment by Wendy67** [comment] 2020-05-05 10:29
yes , I am sure that I "clear all" before.


the complete error is that
PsPM: loading defaults ... 
警告: Cannot check for updates. 
&gt; In pspm_version at 81
&nbsp; In pspm_init at 28
&nbsp; In pspm at 38
&nbsp; In @(hObject,eventdata)pspm('ppDataPreparation_Callback',hObject,eventdata,guidata(hObject)) 
Failed to load C:\Program Files\MATLAB\R2014a\toolbox\PsPM\pspm_cfg\cfg_mlbatch_appcfg.m
|| 和 &amp;&amp; 运算符的操作数必须能够转换为逻辑标量值。
In file "C:\Program Files\MATLAB\R2014a\toolbox\pspm\ext\matlabbatch\@cfg_branch\subsasgn_check.m" (v380), function "subsasgn_check" at line 22.
In file "C:\Program Files\MATLAB\R2014a\toolbox\pspm\ext\matlabbatch\@cfg_branch\subsasgn.m" (v380), function "subsasgn" at line 80.
In file "C:\Program Files\MATLAB\R2014a\toolbox\PsPM\pspm_cfg\pspm_cfg_import.m" (v803), function "pspm_cfg_import" at line 88.
In file "C:\Program Files\MATLAB\R2014a\toolbox\PsPM\pspm_cfg\pspm_cfg_preparation.m" (???), function "pspm_cfg_preparation" at line 13.
In file "C:\Program Files\MATLAB\R2014a\toolbox\PsPM\pspm_cfg\pspm_cfg.m" (???), function "pspm_cfg" at line 11.
In file "C:\Program Files\MATLAB\R2014a\toolbox\PsPM\pspm_cfg\cfg_mlbatch_appcfg.m" (???), function "cfg_mlbatch_appcfg" at line 20.
In file "C:\Program Files\MATLAB\R2014a\toolbox\pspm\ext\matlabbatch\cfg_util.m" (v380), function "local_initapps" at line 1469.
In file "C:\Program Files\MATLAB\R2014a\toolbox\pspm\ext\matlabbatch\cfg_util.m" (v380), function "cfg_util" at line 743.
In file "C:\Program Files\MATLAB\R2014a\toolbox\pspm\ext\matlabbatch\cfg_util.m" (v380), function "cfg_util" at line 451.
In file "C:\Program Files\MATLAB\R2014a\toolbox\PsPM\pspm_cfg\cfg_add_module.m" (???), function "cfg_add_module" at line 7.
In file "C:\Program Files\MATLAB\R2014a\toolbox\pspm\pspm.m" (v636), function "ppDataPreparation_Callback" at line 354.
In file "C:\Program Files\MATLAB\R2014a\toolbox\matlab\guide\gui_mainfcn.m" (???), function "gui_mainfcn" at line 95.
In file "C:\Program Files\MATLAB\R2014a\toolbox\pspm\pspm.m" (v636), function "pspm" at line 55.
In file "", function "@(hObject,eventdata)pspm('ppDataPreparation_Callback',hObject,eventdata,guidata(hObject))" at line 0.

出错 cfg_util (line 428)
rev = '$Rev: 380 $';

调用 "C:\Program Files\MATLAB\R2014a\toolbox\pspm\ext\matlabbatch\cfg_util.m&gt;cfg_util" 时，未对输出参数 "varargout" (可能还包括其他参数)赋值。

出错 cfg_add_module (line 9)
mod_job_id = cfg_util('addtojob', cjob, mod_cfg_id);

出错 pspm&gt;ppDataPreparation_Callback (line 354)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; cfg_add_module('pspm.prep.import');

出错 gui_mainfcn (line 95)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; feval(varargin{:});

出错 pspm (line 55)
&nbsp;&nbsp;&nbsp; gui_mainfcn(gui_State, varargin{:});

出错 @(hObject,eventdata)pspm('ppDataPreparation_Callback',hObject,eventdata,guidata(hObject))

&nbsp;
Error while evaluating uicontrol Callback





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Filip Melinscak"<notifications@github.com&gt;; 
发送时间: 2020年5月5日(星期二) 晚上6:18
收件人: "bachlab/PsPM"<PsPM@noreply.github.com&gt;; 
抄送: "温秀娟"<765487253@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [bachlab/PsPM] although I use MATLAB2014a ，“Error while evaluating uicontrol Callback ”，how I can solve this problem (#112)





 
One way for this error to occur is to clear the Matlab workspace with "clear all;" after initiating the PsPM GUI with "pspm;". Once PsPM is initialized, the memory shouldn't be cleared. Could you confirm if this is what happened?

**Comment by irojkov-ph** [comment] 2020-05-05 11:48
What I see right now is that you apparently have two PsPM toolboxes installed on your machine:
- `C:\Program Files\MATLAB\R2014a\toolbox\pspm\`
- `C:\Program Files\MATLAB\R2014a\toolbox\PsPM\`

And while executing your code it keeps calling functions from one and the other alternatively. What I propose you to do is to delete completely the PsPM version**s** you have right now and reinstall it from scratch !

**Comment by Wendy67** [comment] 2020-05-05 12:30
Thanks for your reply. I think that is not the reason. Because I confirm that I have only one .&nbsp; I think that the toolbox is not fit for MATLAB 2014a. ——Wendy




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "irojkov-ph"<notifications@github.com&gt;; 
发送时间: 2020年5月5日(星期二) 晚上7:48
收件人: "bachlab/PsPM"<PsPM@noreply.github.com&gt;; 
抄送: "温秀娟"<765487253@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [bachlab/PsPM] although I use MATLAB2014a ，“Error while evaluating uicontrol Callback ”，how I can solve this problem (#112)





 
What I see right now is that you apparently have two PsPM toolboxes installed on your machine:
  
C:\Program Files\MATLAB\R2014a\toolbox\pspm\
 
C:\Program Files\MATLAB\R2014a\toolbox\PsPM\
  
And while executing your code it keeps calling functions from one and the other alternatively. What I propose you to do is to delete completely the PsPM versions you have right now and reinstall it from scratch !

**Comment by fmelinscak** [comment] 2020-05-05 14:28
> yes , I am sure that I "clear all" before.

It seems I have not made myself clear. I am saying that you should __not__ do `clear all` after loading the PsPM GUI with `pspm`. If you do `clear all` after doing `pspm`, you will trigger the "Error while evaluating uicontrol Callback" problem. This doesn't have anything to do with the Matlab version as far as I know. 

And although what @irojkov-ph mentioned regarding having two installations of PsPM on the Matlab path might be unrelated to this particular error, it is not a good idea to have two installations in the Matlab path, with the installation paths differing only in letter case. Our recommendation is to have a project-specific PsPM installation (in a subfolder of the analysis project), and to add it to path when you are working on the project.

**Comment by Wendy67** [comment] 2020-05-05 14:58
I am sure that I only have one version. Sorry, I can't understand what happen. When I load the toolbox, it often remind me that remove spm software from path. But I can't find "spm" search path and remove it. I don't know if the reason that I can't use the toolbox. PS:SPM is a toolboox that I use to process image data. ——Wendy




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Filip Melinscak"<notifications@github.com&gt;; 
发送时间: 2020年5月5日(星期二) 晚上10:28
收件人: "bachlab/PsPM"<PsPM@noreply.github.com&gt;; 
抄送: "温秀娟"<765487253@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [bachlab/PsPM] MATLAB2014a, “Error while evaluating uicontrol Callback ” (#112)





  
yes , I am sure that I "clear all" before.
  
It seems I have not made myself clear. I am saying that you should not do clear all after loading the PsPM GUI with pspm. If you do clear all after doing pspm, you will trigger the "Error while evaluating uicontrol Callback" problem. This doesn't have anything to do with the Matlab version as far as I know.
 
And although what @irojkov-ph mentioned regarding having two installations of PsPM on the Matlab path might be unrelated to this particular error, it is not a good idea to have two installations in the Matlab path, with the installation paths differing only in letter case. Our recommendation is to have a project-specific PsPM installation (in a subfolder of the analysis project), and to add it to path when you are working on the project.

**Comment by irojkov-ph** [comment] 2020-05-14 13:16
Hi Wendy,
We haven't received any news from you about your issue. We are still of the opinion that it is specific to your machine and not to the PsPM toolbox. The issue should be solved by reinstalling MATLab and PsPM as we have mentioned previously.
I close the issue for now but feel free to open a new one if the problem is still relevant !
Ivan.

**Closed** 2020-05-14 13:16 UTC
Labels: help wanted

**Comment by Wendy67** [comment] 2020-05-14 13:35
ok,thanks for your&nbsp; help.– wendy



---Original---
