### ISSUE TITLE
Failure to import BrainVision data

### ISSUE THREAD

**Issue by Maren186** [bachlab/PsPM#209] opened 2021-04-12 08:42 UTC
Hello,

I've been trying to import BrainVision data using the PsPM Batch Editor. 
I specified the Data File (.eeg) and tried both to import the SCR Channel alone and also different Channels (SCR, ECG, Startle) at the same time. 

I unfortunately always got the same error message: 
12-Apr-2021 10:31:54 - Failed  'Import'
Unrecognized function or variable 'filename'.
In file "C:\Users\...\PsPM_5.0.0\Import\fieldtrip\fileio\ft_read_header.m" (v395), function "ft_read_header" at line 114.
In file "C:\Users\...\PsPM_5.0.0\pspm_get_brainvis.m" (???), function "pspm_get_brainvis" at line 28.
In file "C:\Users\...\PsPM_5.0.0\pspm_import.m" (???), function "pspm_import" at line 201.
In file "C:\Users\...\PsPM_5.0.0\pspm_cfg\pspm_cfg_run_import.m" (???), function "pspm_cfg_run_import" at line 118.
The following modules did not run:
Failed: Import

I couldn't find the solution for my problem and unfortunately importing the file manually through the Command Window did not work either.
I would be very thankful if you can help me with my problem or give me some general advice about how to use PsPM to properly import BrainVision data files.

Thank you very much. 
Best regards, Maren 

### Technical Info
* PsPM version: Version 5.0.0 (21.08.2020)
* MATLAB version: Matlab 2021a

**Comment by teddychao** [comment] 2021-04-12 12:23
Dear @Maren186 

Thank you for the description of this issue. We have understood the issue mentioned in this comment.
Could we have some sample data so we can replicate this issue and find the reason?

Kind regards
Teddy

**Comment by Maren186** [comment] 2021-04-12 12:47
Dear Teddy,

Thank your for your quick response!
How can I send/give you example data? (My file is 50.000 KB big and too big to be attached..)

Kind regards
Maren

**Comment by teddychao** [comment] 2021-04-13 02:47
Dear @Maren186 

Thanks for your patience and the provided files.
Based on the given documents and the version of software, the reason that leads to the issue is that, the provided files for BrainVision data importing. The current version of PsPM would expect that, if Brainvision_eeg is imported, a file of .egg and a file of .vhdr should be provided together. I checked the provided data and I guess .vhdr was not provided in the target folder where .eeg file was placed.
At the current stage, I would suggest to check if a .vhdr file could be available. If so, I would suggest to put the .vhdr file at the same location and rename it with the same name to the .eeg file. Ideally, the BrainVision data should be able to be imported. Please feel free to let me know if it works after that.
Thanks.

Best wishes,
Teddy

**Comment by Maren186** [comment] 2021-04-13 06:33
Dear @teddychao 

Thanks for your answer.
Unfortunately I only have .ahdr files for that subject. I will check whether I can still get .vhdr files with the data I have.
I have another dataset with .vhdr files: https://drive.google.com/file/d/16I8cCq70dU5aJl3tkmZIhuJqjwt2Q1XV/view?usp=sharing
How can I select both files when importing the data with PsPM? Using the batch editor and going to the folder where my data is located I can unfortunately only select the .eeg but not the .vhdr file.

Thanks.
Best regards,
Maren

**Comment by teddychao** [comment] 2021-04-13 13:15
Dear @Maren186 

Thanks for the questions and the provided documents.
Please kindly import the BrainVision data like this, and theoretically it can be imported successfully.
<img width="882" alt="image" src="https://user-images.githubusercontent.com/3895146/114558144-48f9f180-9c62-11eb-8439-8b96993ff4ea.png">
<img width="600" alt="image" src="https://user-images.githubusercontent.com/3895146/114558163-4eefd280-9c62-11eb-88d7-012cffdadba9.png">

In PsPM, the vdhr file is not required to be set in the batch editor, because it will be automatically detected if it is with the same name to the eeg file. If you put the vdhr file in the same folder of eeg file, then it will be used automatically.

I hope it helps, and please feel free to let me know if you have further questions 🙂
Thanks.

Best regards,
Teddy

**Comment by Maren186** [comment] 2021-04-13 15:04
Dear @teddychao,

Thank you very much for all your help!
Unfortunately it still does not work for me.
![Batch-Editor](https://user-images.githubusercontent.com/72658453/114575175-34295800-9c7a-11eb-973f-3740c20ab5b2.PNG)
![Error-Message](https://user-images.githubusercontent.com/72658453/114575182-35f31b80-9c7a-11eb-996a-3539771f921a.PNG)
I attachted you my Batch editor screenshot and the error message I always receive. 
Maybe you have any idea left why the import is wokring for you, but not for me.

Thank you very much.

Best regards,
Maren

**Comment by teddychao** [comment] 2021-04-13 16:34
Dear @Maren186 

Thanks for the description of the issue and the screenshots.
Could you please send me the error information?
When the software generate an issue, it will give you a dialog to ask whether the error information should be saved. Please click Yes and save it. I can investigate where the issue comes from 🙂
<img width="544" alt="image" src="https://user-images.githubusercontent.com/3895146/114588332-7bb1e300-9c7e-11eb-80ad-2188de302637.png">
Thanks!

Best wishes,
Teddy

**Comment by Maren186** [comment] 2021-04-13 16:41
Dear @teddychao,

Thank you very much! 
Here's the file: https://drive.google.com/file/d/1hUvWQDYAEeObWLfDYvZV2KNna8mWQH_L/view?usp=sharing

Thanks!
Best wishes,
Maren

**Comment by teddychao** [comment] 2021-04-13 17:45
Dear @Maren186 

Thank you for the document.
Maybe I am wrong, but could I ask you to confirm there is no space appearing in the path of the document?
I am not sure Microsoft Windows handles space well in the path. In Apple Macintosh, the path is normally written like "Users/Name/Test\ 1" if there is a folder "Test 1" at the home folder.
Please feel free to let me know if it works. Thanks 🙂

Best wishes,
Teddy

**Comment by Maren186** [comment] 2021-04-14 06:20
Dear @teddychao  

I checked it this morning. Actually there was a space appearing in the path which I deleted now.
My path ist now: C:\Users\maren\Desktop\Praktikum\BrainVision\BB_freezing0005
Unfortunately this doesn't change the error message.
I don't know whether the saved error information changed, so here's the current version: https://drive.google.com/file/d/1tifnpsp4sg2CPYjqXno9FbEA4jE2mqor/view?usp=sharing

Thank you very much!

Best wishes,
Maren

**Comment by teddychao** [comment] 2021-04-14 16:22
Dear @Maren186 

Thank you for your patience. I guess the issue could be caused by the settings at some location. Based on the provided data, I have tested on the MATLAB online and it tells me the data has been imported. I am not sure if we have set the same values for all the settings. Therefore, could I ask you to try the [MATLAB online](https://matlab.mathworks.com) here and see if you still get the error at the online version. The source code of PsPM with the files stored in the folder _bug_ can be found [here](https://drive.matlab.com/sharing/8ab6d119-1442-4c6a-bd84-5f6304337545).
Please feel free to let me know if the error can be replicated at MATLAB online 🙂

Thanks.

Best wishes,
Teddy

**Comment by Maren186** [comment] 2021-04-15 10:07
Dear @teddychao 

Thank you very much. Unfortunately my univeristy license does not include MatLab Online but I will check in with my colleauges and ask whether someone has access to MatLab Online.

Thank you very much!

Best wishes,
Maren

**Comment by dominikbach** [comment] 2021-04-29 11:46
Hi Maren, were you able to resolve the problem or do you still need help? Perhaps we could do a Teams/Zoom session with screensharing? Dominik

**Comment by Maren186** [comment] 2021-04-29 12:43
Hi @dominikbach,
unfortuneately I couldn't find a solution for my problem yet.
If you had time for a Zoom/Teams meeting next week, I would gladly take the offer! 
Kind regards
Maren

**Comment by teddychao** [comment] 2021-04-29 13:26
> Hi @dominikbach,
> 
> unfortuneately I couldn't find a solution for my problem yet.
> 
> If you had time for a Zoom/Teams meeting next week, I would gladly take the offer! 
> 
> Kind regards
> 
> Maren

Hi Maren,

I'm sorry to know the problem has not been resolved through the previous solution.
Could I know if you are happy to join a meeting with me on Zoom or Microsoft Teams? I can try to find out how to resolve this if the screen can be shared.

Thanks

Best wishes 
Teddy

**Comment by Maren186** [comment] 2021-04-29 14:49
Hi @teddychao,
Sure! That would be great! Unfortunately I only have time next week from Tuesday on. Is there any time (ideally between 8 & 12) that would fit your schedule? 
Thanks and best whishes,
Maren

**Comment by teddychao** [comment] 2021-05-03 13:23
> Hi @teddychao,
> Sure! That would be great! Unfortunately I only have time next week from Tuesday on. Is there any time (ideally between 8 & 12) that would fit your schedule?
> 
> To make things easier I will just suggest some time slots:
> Wednesday (5.05): between 8 and 13 o'clock (UTC+2)
> Thrusday (6.05): between 8 and 11.30 o'clock (UTC+2)
> Friday (7.05): between 10 and 16 o'clock (UTC+2)
> Saturday (8.05): between 11 and 13 o'clock (UTC+2)
> 
> Thanks and best whishes,
> Maren

Thanks Maren. Can we meet up on Wednesday 10am? I will send you the zoom meeting invitation if the time works well for you 😀 Thanks!

Best wishes,
Teddy

**Comment by Maren186** [comment] 2021-05-03 15:28
Hi @teddychao,
11 am my side sounds perfect! Thanks and till Wednesday! :) 
Best wishes,
Maren

**Comment by teddychao** [comment] 2021-05-03 16:19
> Hi @teddychao,
> 11 am my side sounds perfect! Thanks and till Wednesday! :)
> Best wishes,
> Maren

Hi @Maren186
Many thanks for the confirmation. Please use the link below to join the meeting on Wednesday if you don't mind. 😀

> Topic: PsPM Issue Zoom Meeting
> Time: May 5, 2021 10:00 AM London
> 
> Join Zoom Meeting
> https://bham-ac-uk.zoom.us/j/87177231265?pwd=VlZBZFcvdDV4ZjlzNjUwZm54WUJBdz09
> 
> Meeting ID: 871 7723 1265
> Passcode: 038834

Best wishes
Teddy

**Comment by teddychao** [comment] 2021-05-04 01:47
Hi @Maren186 
Apologies, I did not see the meeting arranged at 10am on Wednesday in our centre. Could we know if 9am GMT (10am European time) is ok? If not, we can still meet up at 10am anyway 🙂
Apologies again.

Best wishes,
Teddy

**Comment by Maren186** [comment] 2021-05-04 10:06
Hi @teddychao,
unfortunately I have another meeting at 9.30 (8.30 your time). But we could also meet on 10.30 (11.30 your time) if that is better for you? Otherwise we could also meet on thursday morning before 12 am my time.
Just let me know which option fits best for you!
Best wishes,
Maren

**Comment by teddychao** [comment] 2021-05-04 12:10
Hi @Maren186 
Yes! Many thanks Maren. 10:30 (11:30 here) is a better time to me. I have updated the time for our meeting through Zoom. We can still use that link to join the meeting.
Many thanks again.
Best wishes,
Teddy

**Comment by Maren186** [comment] 2021-05-04 14:03
Hi @teddychao,
Thanks! See you tomorrow at 11.30am (10.30 for me)!
Best wishes, 
Maren

**Comment by teddychao** [comment] 2021-05-07 02:10
Hi @Maren186 

I have investigated the case. It seems that the shared eeg data is using the *amrk* and *ahdr* extensions. However, PsPM would expect there are *vmrk* and *vhdr* files. These are recommended by [the Donders Institute for Brain, Cognition and Behaviour](https://www.fieldtriptoolbox.org). Could I know all the eeg data you have obtained are with the *amrk* and *ahdr* extensions?

**Comment by Maren186** [comment] 2021-05-07 08:49
Hi @teddychao,

I sent you an e-mail this morning, I hope you received it. All my data is ahdr right now, but ahdr files should be convertable to vhdr, so I tried to convert them with the BrainVision analyzer but unfortunately some (different) error messages still occur. Here are my converted files: https://drive.google.com/file/d/1OPEKMOJSvYAm8Y8qIwjsk24MSW6dhKjl/view?usp=sharing 
And here is the error message: https://drive.google.com/file/d/1bJTxZlzcjpn-aprG7LKTM678g0RXyQr1/view?usp=sharing and https://drive.google.com/file/d/1s8RCb64n4BL5gmT6VpvKSRNcsUQUYUzK/view?usp=sharing

Thank you very much!
Best regards,
Maren

**Comment by teddychao** [comment] 2021-05-07 19:17
Hi @Maren186 

Many thanks for the updates. I have got the useful documents and mat files.
Could I ask if the message you met is shown like this?
<img width="598" alt="Screenshot 2021-05-07 at 20 15 35" src="https://user-images.githubusercontent.com/3895146/117498061-2dd48600-af71-11eb-9341-9fca85b7c406.png">
Thanks!
Best wishes,
Teddy

**Comment by Maren186** [comment] 2021-05-08 06:40
Hi @teddychao,
yeah that's the same error message I get (for channel 1 to channel 5).
![grafik](https://user-images.githubusercontent.com/72658453/117529649-f8638300-afd8-11eb-9d7c-bbe68d37d647.png)
Thanks!
Best wishes,
Maren

**Comment by dhewitt16** [comment] 2023-10-11 15:43
Hi @teddychao @Maren186 - Did you manage to resolve this issue?
I am also struggling to import BrainVision data and it appears to be a similar issue, but I can't find if there was a solution listed in the thread? 

My error message is:

------------------------------------------------------------------------
11-Oct-2023 16:36:41 - Running job #1
------------------------------------------------------------------------
11-Oct-2023 16:36:41 - Running 'Import'
11-Oct-2023 16:36:42 - Failed  'Import'
Error using read_brainvision_vhdr
cannot determine the location of the data file p12_cond_b1.eeg
In file "/Users/dhewitt/Analysis/PsPM6.1/Import/fieldtrip/fileio/private/read_brainvision_vhdr.m" (v395), function "read_brainvision_vhdr" at line 71.
In file "/Users/dhewitt/Analysis/PsPM6.1/Import/fieldtrip/fileio/ft_read_header.m" (v395), function "ft_read_header" at line 455.
In file "/Users/dhewitt/Analysis/PsPM6.1/pspm_get_brainvis.m" (???), function "pspm_get_brainvis" at line 29.
In file "/Users/dhewitt/Analysis/PsPM6.1/pspm_import.m" (???), function "pspm_import" at line 246.
In file "/Users/dhewitt/Analysis/PsPM6.1/pspm_cfg/pspm_cfg_run_import.m" (???), function "pspm_cfg_run_import" at line 117.

The following modules did not run:
Failed: Import
If the problem can be fixed without modifying the job, the computation can be resumed by running
   cfg_util('cont',1)
from the MATLAB command line.

The log file can be found here: https://www.dropbox.com/s/shv1li7s2se53aa/error.mat?dl=0

**Comment by teddychao** [comment] 2023-10-11 15:48
> Hi @teddychao @Maren186 - Did you manage to resolve this issue? I am also struggling to import BrainVision data and it appears to be a similar issue, but I can't find if there was a solution listed in the thread?
> 
> My error message is:
> 
> ## 11-Oct-2023 16:36:41 - Running job #1
> 11-Oct-2023 16:36:41 - Running 'Import' 11-Oct-2023 16:36:42 - Failed 'Import' Error using read_brainvision_vhdr cannot determine the location of the data file p12_cond_b1.eeg In file "/Users/dhewitt/Analysis/PsPM6.1/Import/fieldtrip/fileio/private/read_brainvision_vhdr.m" (v395), function "read_brainvision_vhdr" at line 71. In file "/Users/dhewitt/Analysis/PsPM6.1/Import/fieldtrip/fileio/ft_read_header.m" (v395), function "ft_read_header" at line 455. In file "/Users/dhewitt/Analysis/PsPM6.1/pspm_get_brainvis.m" (???), function "pspm_get_brainvis" at line 29. In file "/Users/dhewitt/Analysis/PsPM6.1/pspm_import.m" (???), function "pspm_import" at line 246. In file "/Users/dhewitt/Analysis/PsPM6.1/pspm_cfg/pspm_cfg_run_import.m" (???), function "pspm_cfg_run_import" at line 117.
> 
> The following modules did not run: Failed: Import If the problem can be fixed without modifying the job, the computation can be resumed by running cfg_util('cont',1) from the MATLAB command line.
> 
> The log file can be found here: https://www.dropbox.com/s/shv1li7s2se53aa/error.mat?dl=0
> 
> Note: I am trying to upload the .eeg data. The .vhdr and .vmrk data is in the same directory with the same name.

Hi @dhewitt16 Thanks for posting the data. I do not quite remember the issue. Since you have made the data available to us, i will now try to get the data and see what is going on.

**Comment by dhewitt16** [comment] 2023-10-16 05:52
Hi @teddychao - thanks! I worked out that the issue is from renaming the files, as the file name is not the same as it is stored in the header file. Usually when renaming all the BrainVision files (.eeg, .vhdr and .vmrk), EEGLAB is able to resolve the inconsistencies with the name stored inside the vhdr file, but here it was not. The issue can be resolved by making sure the name of the .eeg file is the same as the name in the vhdr file (i.e., not just the vhdr filename itself).

**Comment by dominikbach** [comment] 2024-04-25 17:15
Issue was solved.

**Closed by dominikbach** 2024-04-25 17:15 UTC
