### ISSUE TITLE
fail to lauch pspm in matlab2018a, ubuntu 22.04,

### ISSUE THREAD

**Issue by yingjieQ** [bachlab/PsPM#555] opened 2023-12-06 18:07 UTC
### Steps to Reproduce
1. addpath('.../PsPM6.1');
2. type 'pspm' in command window

### Expected Results
pspm GUI
### Actual Results
error: >> pspm
Unrecognized property 'Tooltip' for class 'matlab.ui.control.Button'.

Error in pspm_appdesigner/createComponents (line 254)
            app.button_quit.Tooltip = 'Goodbye.';

Error in pspm_appdesigner (line 509)
            createComponents(app)

Error in pspm (line 12)
    pspm_appdesigner
### Technical Info
* PsPM version: 6.1.0
* MATLAB version: 2018a

**Comment by teddychao** [comment] 2023-12-06 21:31
Dear @yingjieQ 
Thank you for reporting the issue.
The Linux version of PsPM has not been actively maintained in the past year since most users are using Windows. However, we aim at making PsPM consistently stable between the three OS families, thus the issue will be fixed. Please allow us some time to make Ubuntu available for replicating and solving the issue. Thank you for your patience.
Best wishes
Teddy

**Comment by teddychao** [comment] 2023-12-10 21:02
Dear @yingjieQ 
Thank you for your patience to this issue. We have tried to replicate the issue on MATLAB 2023b and Ubuntu 22.04, but we could not replicate the issue. Please find the animation attached in this response. May we ask if the issue is replicable on MATLAB 2023b or just happening on MATLAB 2018a?
Best wishes
Teddy

**Comment by yingjieQ** [comment] 2023-12-11 13:47
Hi Teddy,

Yes, I think this is matlab 2018a specific, because this is the matlba version we have on our server for analyzing data. I never tried on the mewest matlab. It'd be great if it's possible for you to also check on this version of matlab.

Yingjie

**Comment by teddychao** [comment] 2023-12-18 03:23
Dear @yingjieQ 

Thank you for providing the further information for this issue. We have now proposed a solution that may be able to solve this issue. Before the release of PsPM that contains the patch, I would recommend using "pspm_guide" in Terminal to start PsPM instead of using "pspm", because this will force PsPM to call the old guide version GUI. I have tested this solution on MATLAB 2018 on linux and I think it works for me. Please feel free to let me know if it works for you.
Best wishes
teddy

**Closed** 2023-12-18 13:49 UTC
Labels: Waiting for Feedbacks

**Comment by teddychao** [comment] 2023-12-18 13:58
Hi @yingjieQ 
Thank you for reporting the new issue.
Could you please let us know if you were starting up PsPM at the path of PsPM 6.1?
For your information, here is the screen recording of starting up PsPM at MATLAB 2018a on Ubuntu (latest version).

https://github.com/bachlab/PsPM/assets/3895146/b1a7a6c4-cf79-4250-a3ce-ef335502151b

Hope it helps.
Best wishes
Teddy

**Comment by yingjieQ** [comment] 2023-12-18 14:41
Hi Teddy,

I thought I did, but this time when I tried again for a few times, running pspm_guide in the folder or addpath(...), it seems to be working. Thanks for helping!

Best,
Yingjie

**Comment by teddychao** [comment] 2023-12-18 14:43
Hi @yingjieQ 
This is great, thank you for letting us know. If there are further questions, please feel free to let us know.
Best wishes
Teddy
