### ISSUE TITLE
GUI issues in version 6.1.1

### ISSUE THREAD

**Issue by teddychao** [bachlab/PsPM#591] opened 2024-01-19 14:55 UTC
### Summary
Several issues appear in version 6.1.1 and they seem to be caused by the incorrect / unmanaged variables in the GUI rather than the functions.

Relevant functions are:
- pspm_find_validfixation 
  - "all eyes" and "combined eyes" appear at the same time?
- pspm_glm
  - Specifying "overwrite" is not possible for `pspm_glm` through the GUI.
  - GLM for SPS does not parse the modelling properly if "best eye" is selected.
- pspm_process_illuminance 
  - Through the GUI, `options.missing` can be specified as "no missing epochs", but this information raises an error saying "Warning: options.missing has an invalid value.
### Technical Info
* PsPM version: 6.1.1
* MATLAB version: 2023b

**Comment by iPsych** [comment] 2024-01-21 02:11
GUI data display can't draw wave at all in Matlab 2022b in MacOS. Tested with both my data and tutorial data.
I guess the current gui works properly with very specific version of matlab.

`Index in position 1 exceeds array bounds. Index must not exceed 1.
`

**Comment by teddychao** [comment] 2024-01-21 02:41
> GUI data display can't draw wave at all in Matlab 2022b in MacOS. Tested with both my data and tutorial data. I guess the current gui works properly with very specific version of matlab.
> 
> `Index in position 1 exceeds array bounds. Index must not exceed 1. `

Hi @iPsych 
Thank you so much for posting the issue here. The warning means the data transferred at the specific line was empty and therefore cannot be read. We would be grateful if you could let us know which tutorial data you are using.
Best wishes
Teddy

**Comment by iPsych** [comment] 2024-01-21 02:46
Hello @teddychao,
Thanks for the reply. Possibly it might caused by my data conversion script. Can I find any properly converted .mat file with 'markerinfo' type channel somewhere?
The issue is not happened for .mat converted from .smr in GLM tutorial, but SCRV_4_spike_01.mat shows same error.

**Comment by dominikbach** [comment] 2024-05-07 12:16
All issues are solved in current develop version with one exception: data channel selection for GLM has not been implemented in #666 (only marker channel was implemented). This will be fixed in a future PR.

**Closed** 2024-06-10 15:30 UTC
Labels: Bug, Urgent
