### ISSUE TITLE
us_shift option of pspm_bf_psrf_fc

### ISSUE THREAD

**Issue by SerenXia** [bachlab/PsPM#238] opened 2021-06-14 16:18 UTC
### Summary
I tried to plot fear-conditioned pupil size response function by calling the RF in PsPM:
[bf, x] = pspm_bf_psrf_fc(TD, cs, cs_d, us, us_shift)
The ps response time locked to CS onset, but if I understood correctly, under the umbrella of us, we can set different SOA with us_shift (default us_shift = 3.5). However, no matter how I called the function:
[bf, x] = pspm_bf_psrf_fc(TD) % so by default, cs = 1, cs_d = 0, us = 0, us_shift = 3.5
[bf, x] = pspm_bf_psrf_fc(TD, 1, 0, 1, 7)
[bf, x] = pspm_bf_psrf_fc(TD, 1, 1, 1, 7)

The plotted response functions are always the same ones, i.e. us_shift does not change or shift the response function.

Not sure if this is bug, but it would be better if we can clarify this "us_shift" in case it is not a bug.

### Technical Info
* PsPM revision ID: 5.0.0
* MATLAB version: 9.5.0.1178774 (R2018b) Update 5

**Comment by teddychao** [comment] 2022-01-24 13:57
Hi @SerenXia 

Thanks for posting the issue. I may misunderstand the details as I tried to re-generate the issues but I saw slight difference there. Here are the examples where I set a randomly picked TD which I think could be wrong. Could you please let me know how you set `TD` or other parameters and how the plots look like, which really helps me to find the reason of the issue.

Thanks.
![Untitled 1](https://user-images.githubusercontent.com/3895146/150795925-bbb09c5f-a0d5-40d7-a201-00ceff5c6ffe.png)
![Untitled 2](https://user-images.githubusercontent.com/3895146/150795941-397898dc-3a08-471b-b279-7449a222d36d.png)
![Untitled 3](https://user-images.githubusercontent.com/3895146/150795952-396aaff1-be04-4286-a9ed-a93e28d3e7b7.png)

**Comment by dominikbach** [comment] 2023-09-29 08:24
I cannot reproduce the error in PsPM 6.1. Closed as resolved.

**Closed by dominikbach** 2023-09-29 08:24 UTC
Labels: Waiting for Feedbacks
